name: Smart Drawer CI/CD - Build Only

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main" ]
  release:
    types: [published]

permissions:
  contents: write
  checks: write
  pull-requests: write

jobs:
  build:
    name: Build APK Only
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build debug APK
      run: ./gradlew assembleDebug --stacktrace

    - name: Upload debug APK
      uses: actions/upload-artifact@v4
      with:
        name: smart-drawer-debug
        path: app/build/outputs/apk/debug/app-debug.apk

    - name: Build release APK
      if: github.event_name == 'release'
      run: ./gradlew assembleRelease --stacktrace

    - name: Upload release APK to GitHub Release
      if: github.event_name == 'release'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: app/build/outputs/apk/release/app-release.apk
        asset_name: smart-drawer-release.apk
        asset_content_type: application/vnd.android.package-archive 